---
apiVersion: v1
data:
  private.pem: xxx==
  public.pem: xxx==
kind: Secret
metadata:
  name: server-auth-keys
type: Opaque

---
apiVersion: v1
data:
  epaylink_dev_private_key.pem: zzz=
  # epaylink_dev_public_key.pem: zzz=
  tidebit_staging_private.pem: xxx==
  tidebit_staging_public.pem: xxx==
kind: Secret
metadata:
  name: server-ops-keys
type: Opaque