apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-pw-elastic
  namespace: logging
type: Opaque
data:
  username: ${ELASTIC_SEARCH_USERNAME_SECRET}
  password: ${ELASTIC_SEARCH_PASSWORD_SECRET}