---
##################
# Kibana
##################
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kibana-gateway
  namespace: logging
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http2-kibana
      protocol: HTTP2
    hosts:
    - "kibana.${DOMAIN_NAME}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kibana-vs
  namespace: logging
spec:
  hosts:
  - "kibana.${DOMAIN_NAME}"
  gateways:
  - kibana-gateway
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: kibana
        port:
          number: 5601

---
##################
# elasticsearch
##################
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: elasticsearch-gateway
  namespace: logging
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http2-elasticsearch
      protocol: HTTP2
    hosts:
    - "elasticsearch.${DOMAIN_NAME}"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: elasticsearch-vs
  namespace: logging
spec:
  hosts:
  - "elasticsearch.${DOMAIN_NAME}"
  gateways:
  - elasticsearch-gateway
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: elasticsearch-client
        port:
          number: 9200

