---
apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  username: aXN1bm9uZQ== # server
  passphrase: aXN1bm9uZV9raWFsaQ== # server_kiali

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: istio-system
  labels:
    app: grafana
type: Opaque
data:
  username: aXN1bm9uZQ== # server
  passphrase: aXN1bm9uZV9ncmFmYW5h # server_grafana