---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
spec:
  storageClassName: 'cloud-ssd'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
