---
##################
# Mysql
##################
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mysql-gateway
  namespace: database
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 3306
      name: tcp-mysql
      protocol: TCP
    hosts:
    - "mysql.${DOMAIN_NAME}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mysql-vs
  namespace: database
spec:
  hosts:
  - "mysql.${DOMAIN_NAME}"
  gateways:
  - mysql-gateway
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: mysql
        port:
          number: 3306